DEFAULT_MAX_ROUNDS = 3
DEFAULT_MAX_WORKERS_PER_ROUND = 3
DEFAULT_SLIDING_WINDOW_SIZE = 10
DEFAULT_CONTEXT_EVENT_LIMIT = 14
DEFAULT_CONTEXT_CHAR_BUDGET = 6000
DEFAULT_MEMORY_SEARCH_K = 4
DEFAULT_MEMORY_WRITE_SCORE = 70
